### ISSUE TITLE
You can make a video tutorial on running the code. I hope you do it on youtube. thank you

### ISSUE THREAD

**Issue by cuong369** [yonilx/Siamese-LSTM#1]
python version ???
library sets: tensorflow version ??, gensim version ??, vvv ...
You can make a video tutorial on running the code. I hope you do it on youtube. thank you

**Comment by jonzarecki** [comment]
Don't think I'll have the time to post a video on YouTube, but I've updated the info in the readme.
As for running the code all the train_* files should be runnable (in the main folder and alternative_trains) as well as the files in the examples folder
