### ISSUE TITLE
failed in download!!! how to download? Can you provide a link?

### ISSUE THREAD

**Issue by cuong369** [yonilx/Siamese-LSTM#2]
Download the word2vec model from https://code.google.com/archive/p/word2vec/

**Comment by jonzarecki** [comment]
The link you provided is correct, you should check for the reason the download failed. 
The actual link for downloading the w2v file is [this](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing), note this is a zipped file.
